version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go-server
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@db:5432/app_db?sslmode=disable

volumes:
  postgres_data: